CREATE TABLE IF NOT EXISTS books (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price INT,
    available BOOLEAN DEFAULT TRUE,
    purchasable BOOLEAN DEFAULT TRUE,
    cover_url VARCHAR(500)
);